# Generated by Django 5.2.17 on 2026-10-10 17:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0003_alter_result_state_resultcorrection'),
        ('students', '0002_applicationdocument_waitlistentry_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicStanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tier', models.CharField(choices=[('good', 'Good standing'), ('probation', 'Probation'), ('suspension', 'Suspension'), ('dismissal', 'Dismissal')], default='good', max_length=12)),
                ('cumulative_gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('computed_at', models.DateTimeField(blank=True, null=True)),
                ('as_of_term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='academics.term')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='standing', to='students.student')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['student'],
            },
        ),
        migrations.CreateModel(
            name='StandingDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('previous_tier', models.CharField(choices=[('good', 'Good standing'), ('probation', 'Probation'), ('suspension', 'Suspension'), ('dismissal', 'Dismissal')], max_length=12)),
                ('tier', models.CharField(choices=[('good', 'Good standing'), ('probation', 'Probation'), ('suspension', 'Suspension'), ('dismissal', 'Dismissal')], max_length=12)),
                ('cumulative_gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('is_automatic', models.BooleanField(default=True)),
                ('reason', models.CharField(blank=True, help_text='Set on a manual override or an appeal outcome; blank for an automatic nightly computation', max_length=300)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('standing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='standing.academicstanding')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='academics.term')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StandingAppeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grounds', models.TextField()),
                ('heard_at', models.DateTimeField(blank=True, null=True)),
                ('outcome', models.CharField(blank=True, choices=[('upheld', 'Appeal upheld'), ('denied', 'Appeal denied')], max_length=10)),
                ('outcome_reason', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('heard_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('decision', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='appeal', to='standing.standingdecision')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='academicstanding',
            index=models.Index(fields=['tier'], name='standing_ac_tier_dbaa68_idx'),
        ),
    ]
