# Generated by Django 5.2.17 on 2026-09-29 12:27

import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programmes', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='e.g. 2026-2027', max_length=12, unique=True)),
                ('starts', models.DateField()),
                ('ends', models.DateField()),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-starts'],
            },
        ),
        migrations.CreateModel(
            name='CourseOffering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='e.g. AGR101-2026-27-S1-MRP', max_length=40, unique=True)),
                ('campus_code', models.CharField(max_length=10)),
                ('lecturer_employee_no', models.CharField(blank=True, help_text='HRMS employee number', max_length=20)),
                ('capacity', models.PositiveIntegerField(default=40)),
                ('coursework_weight', models.DecimalField(decimal_places=2, default=40, max_digits=5)),
                ('exam_weight', models.DecimalField(decimal_places=2, default=60, max_digits=5)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offerings', to='programmes.course')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['term', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Enrolment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('enrolled', 'Enrolled'), ('dropped', 'Dropped'), ('completed', 'Completed')], default='enrolled', max_length=12)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('offering', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrolments', to='academics.courseoffering')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrolments', to='students.student')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['offering', 'student'],
                'unique_together': {('student', 'offering')},
            },
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='e.g. 2026-27-S1', max_length=16, unique=True)),
                ('number', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=60)),
                ('starts', models.DateField()),
                ('ends', models.DateField()),
                ('is_current', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='terms', to='academics.academicyear')),
            ],
            options={
                'ordering': ['-starts'],
                'unique_together': {('year', 'number')},
            },
        ),
        migrations.AddField(
            model_name='courseoffering',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offerings', to='academics.term'),
        ),
        migrations.CreateModel(
            name='GradeBand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('letter', models.CharField(max_length=3)),
                ('min_mark', models.DecimalField(decimal_places=2, max_digits=5)),
                ('points', models.DecimalField(decimal_places=2, max_digits=3)),
                ('is_pass', models.BooleanField(default=True)),
                ('effective_from', models.DateField()),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-effective_from', '-min_mark'],
                'unique_together': {('letter', 'effective_from')},
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coursework_mark', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('exam_mark', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('final_mark', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('letter', models.CharField(blank=True, max_length=3)),
                ('points', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('is_pass', models.BooleanField(null=True)),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted by lecturer'), ('approved', 'Approved by Head of Department'), ('published', 'Published')], default='draft', max_length=12)),
                ('coursework_source', models.CharField(choices=[('manual', 'Entered in the SRMS'), ('lms', 'Received from the LMS')], default='manual', max_length=10)),
                ('decision_comment', models.CharField(blank=True, max_length=300)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('enrolment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='academics.enrolment')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['enrolment'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('coursework_mark__isnull', True), ('coursework_mark__range', (0, 100)), _connector='OR'), models.Q(('exam_mark__isnull', True), ('exam_mark__range', (0, 100)), _connector='OR')), name='result_marks_between_0_and_100')],
            },
        ),
        migrations.AddConstraint(
            model_name='courseoffering',
            constraint=models.CheckConstraint(condition=models.Q(('coursework_weight__gte', 0), ('exam_weight', django.db.models.expressions.CombinedExpression(models.Value(100), '-', models.F('coursework_weight')))), name='offering_weights_total_100'),
        ),
    ]
