# Generated by Django 5.2.18 on 2026-10-06 15:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceTotal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sessions', models.PositiveIntegerField(help_text='Sessions held that took attendance')),
                ('present', models.PositiveIntegerField(default=0)),
                ('late', models.PositiveIntegerField(default=0)),
                ('excused', models.PositiveIntegerField(default=0)),
                ('absent', models.PositiveIntegerField(default=0)),
                ('not_recorded', models.PositiveIntegerField(default=0)),
                ('percent', models.DecimalField(blank=True, decimal_places=2, help_text='Present and late over present, late and absent; empty when nothing was counted', max_digits=5, null=True)),
                ('received_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('enrolment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='academics.enrolment')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['enrolment'],
                'constraints': [models.CheckConstraint(condition=models.Q(('percent__isnull', True), ('percent__range', (0, 100)), _connector='OR'), name='attendance_percent_between_0_and_100')],
            },
        ),
        migrations.CreateModel(
            name='CompetencyResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unit_code', models.CharField(help_text='Unit of competency, e.g. AGR-CROP-001', max_length=40)),
                ('result', models.CharField(choices=[('competent', 'Competent'), ('not_yet_competent', 'Not yet competent')], max_length=20)),
                ('assessed_on', models.DateField()),
                ('source', models.CharField(choices=[('lms', 'Received from the LMS')], default='lms', max_length=10)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('enrolment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competencies', to='academics.enrolment')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['enrolment', 'unit_code'],
                'constraints': [models.UniqueConstraint(fields=('enrolment', 'unit_code'), name='competency_unit_once_per_enrolment')],
            },
        ),
    ]
