# Generated by Django 5.2.17 on 2026-10-10 15:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('students', '0002_applicationdocument_waitlistentry_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='enrolment',
            name='waitlist_rank',
            field=models.PositiveIntegerField(blank=True, help_text="Position in the offering's waitlist; set only while waitlisted", null=True),
        ),
        migrations.AlterField(
            model_name='enrolment',
            name='status',
            field=models.CharField(choices=[('enrolled', 'Enrolled'), ('waitlisted', 'Waitlisted'), ('dropped', 'Dropped'), ('completed', 'Completed')], default='enrolled', max_length=12),
        ),
        migrations.CreateModel(
            name='RegistrationHold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(choices=[('missing_document', 'Missing document'), ('financial', 'Outstanding balance'), ('academic_standing', 'Academic standing'), ('other', 'Other')], max_length=20)),
                ('source', models.CharField(help_text="The process that placed the hold, e.g. 'admissions', 'fees'", max_length=40)),
                ('detail', models.CharField(blank=True, max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registration_holds', to='students.student')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['student', 'is_active'], name='academics_r_student_e7fa60_idx')],
            },
        ),
    ]
