# Generated by Django 5.2.17 on 2026-09-29 12:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('info', 'Information'), ('approval', 'Action required'), ('alert', 'Alert')], default='info', max_length=20)),
                ('title', models.CharField(max_length=160)),
                ('body', models.TextField(blank=True)),
                ('link', models.CharField(blank=True, help_text='In-app route, e.g. /leave/requests/12', max_length=200)),
                ('dedupe_key', models.CharField(blank=True, help_text='Same key per recipient is sent once', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('emailed', models.BooleanField(default=False)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('dedupe_key__gt', '')), fields=('recipient', 'dedupe_key'), name='notification_once_per_recipient_and_key')],
            },
        ),
    ]
