# Generated by Django 5.2.18 on 2026-10-10 18:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0002_applicationdocument_waitlistentry_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvisingNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('advisor_employee_no', models.CharField(help_text='HRMS employee number', max_length=20)),
                ('met_on', models.DateField()),
                ('summary', models.TextField()),
                ('concern', models.CharField(choices=[('none', 'No concern'), ('academic', 'Academic concern'), ('financial', 'Financial concern'), ('attendance', 'Attendance concern'), ('personal', 'Personal or welfare concern')], default='none', max_length=20)),
                ('flagged_for_registrar', models.BooleanField(default=False, help_text='Escalate this note to the Registrar as a concern worth following up')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advising_notes', to='students.student')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-met_on', '-created_at'],
                'indexes': [models.Index(fields=['student', '-met_on'], name='advising_ad_student_13e71e_idx')],
            },
        ),
        migrations.CreateModel(
            name='AdvisorAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('advisor_employee_no', models.CharField(help_text='HRMS employee number', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('ended_reason', models.CharField(blank=True, max_length=300)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advisor_assignments', to='students.student')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['student', 'ended_at'], name='advising_ad_student_f4b51c_idx'), models.Index(fields=['advisor_employee_no', 'ended_at'], name='advising_ad_advisor_846717_idx')],
            },
        ),
    ]
