# Generated by Django 5.2.18 on 2026-10-06 15:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='attendance_required',
            field=models.BooleanField(default=False, help_text='Attendance is a condition of passing; the LMS sends attendance totals for its courses'),
        ),
        migrations.CreateModel(
            name='CourseOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='e.g. LO1', max_length=20)),
                ('text', models.CharField(max_length=500)),
                ('position', models.PositiveSmallIntegerField(default=0, help_text='Order in the course outline')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcomes', to='programmes.course')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['course', 'position', 'code'],
                'constraints': [models.UniqueConstraint(fields=('course', 'code'), name='course_outcome_code_once')],
            },
        ),
    ]
