# Generated by Django 5.2.17 on 2026-10-10 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='intake_capacity',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum applicants admitted per intake year, across all campuses. Blank is unlimited.', null=True),
        ),
    ]
