# Generated by Django 5.2.17 on 2026-09-29 12:27

import core.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programmes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('other_names', models.CharField(blank=True, max_length=120)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('X', 'Other or not stated')], default='X', max_length=1)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('region', models.CharField(blank=True, help_text='Administrative region or country', max_length=40)),
                ('nationality', models.CharField(default='Guyanese', max_length=60)),
                ('student_no', models.CharField(max_length=20, unique=True)),
                ('national_id', core.fields.EncryptedTextField(blank=True, editable=True, null=True)),
                ('campus_code', models.CharField(max_length=10)),
                ('intake_year', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('enrolled', 'Enrolled'), ('deferred', 'Deferred'), ('suspended', 'Suspended'), ('withdrawn', 'Withdrawn'), ('graduated', 'Graduated')], default='enrolled', max_length=20)),
                ('is_residential', models.BooleanField(default=False, help_text='Lives in campus accommodation')),
                ('sponsor', models.CharField(choices=[('self', 'Self-funded'), ('government', 'Government of Guyana'), ('other', 'Other sponsor')], default='self', max_length=20)),
                ('next_of_kin_name', models.CharField(blank=True, max_length=120)),
                ('next_of_kin_phone', models.CharField(blank=True, max_length=40)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='programmes.programme')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('other_names', models.CharField(blank=True, max_length=120)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('X', 'Other or not stated')], default='X', max_length=1)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('region', models.CharField(blank=True, help_text='Administrative region or country', max_length=40)),
                ('nationality', models.CharField(default='Guyanese', max_length=60)),
                ('reference', models.CharField(max_length=20, unique=True)),
                ('qualifications', models.TextField(blank=True, help_text='Summary of entry qualifications')),
                ('campus_code', models.CharField(max_length=10)),
                ('intake_year', models.PositiveSmallIntegerField()),
                ('state', models.CharField(choices=[('received', 'Received'), ('screened', 'Screened'), ('offered', 'Offer made'), ('accepted', 'Accepted and admitted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='received', max_length=20)),
                ('decision_comment', models.CharField(blank=True, max_length=300)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='programmes.programme')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('student', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application', to='students.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['campus_code', 'status'], name='students_st_campus__04eca2_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['programme', 'intake_year'], name='students_st_program_1d74a3_idx'),
        ),
    ]
