# Generated by Django 5.2.17 on 2026-10-10 15:03

import core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

# The admissions states grew more granular (S-W01); these two old codes are renamed so that any
# application already sitting in them on a deployed database keeps a valid, equivalent state.
RENAMED_STATES = {"received": "submitted", "screened": "under_review"}


def rename_old_states(apps, schema_editor):
    Application = apps.get_model("students", "Application")
    for old, new in RENAMED_STATES.items():
        Application.objects.filter(state=old).update(state=new)


def restore_old_states(apps, schema_editor):
    Application = apps.get_model("students", "Application")
    for old, new in RENAMED_STATES.items():
        Application.objects.filter(state=new).update(state=old)


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0002_programme_intake_capacity'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(rename_old_states, restore_old_states),
        migrations.CreateModel(
            name='ApplicationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doc_type', models.CharField(choices=[('transcript', 'School transcript or results'), ('identification', 'Proof of identity'), ('medical', 'Medical certificate'), ('other', 'Other supporting document')], default='other', max_length=20)),
                ('file', models.FileField(upload_to='applications/%Y/', validators=[core.validators.validate_upload])),
                ('note', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WaitlistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('intake_year', models.PositiveSmallIntegerField()),
                ('rank', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['programme', 'intake_year', 'rank'],
            },
        ),
        migrations.AddField(
            model_name='application',
            name='assessment_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='application',
            name='assessment_score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Interview or entrance assessment score, 0-100', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='state',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under review'), ('interview', 'Interview or assessment scheduled'), ('assessed', 'Interview or assessment scored'), ('offered', 'Offer made'), ('waitlisted', 'Waitlisted'), ('accepted', 'Accepted and admitted'), ('declined', 'Declined by the applicant'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='submitted', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.CheckConstraint(condition=models.Q(('assessment_score__isnull', True), ('assessment_score__range', (0, 100)), _connector='OR'), name='application_assessment_score_between_0_and_100'),
        ),
        migrations.AddField(
            model_name='applicationdocument',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='students.application'),
        ),
        migrations.AddField(
            model_name='applicationdocument',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='applicationdocument',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='waitlistentry',
            name='application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entry', to='students.application'),
        ),
        migrations.AddField(
            model_name='waitlistentry',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='waitlistentry',
            name='programme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='waitlist_entries', to='programmes.programme'),
        ),
        migrations.AddField(
            model_name='waitlistentry',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='waitlistentry',
            unique_together={('programme', 'intake_year', 'rank')},
        ),
    ]
